# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dfd0a33a8627da583bb50fb44609ee716bb14fee2f7b89c852a255bb7a2c36638d284039514f44e2aae946c34f3aec92dc628002b52ddf53bf2c790cd467578f

test:
  secret_key_base: d92fa6889d5767b5cba8c87fb5cf6dc011281abc994ec43c57c091cf15ea728d4393db783d56d7c9d7378e62bd6cbb9a3c232ff1bd3a6a12f3eaac48b329ac70

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
